Cds.TestDashboard.Web/Controllers/JenkinsBuildController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cds.TestDashboard.Web.Controllers
{
    using Cds.TestDashboard.Core.Models.Pages;
    using Cds.TestDashboard.Core.Workers.Interfaces;
    using JenkinsNET.Models;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Filters;
    using Microsoft.AspNetCore.Mvc.ViewEngines;
    using Microsoft.Extensions.Logging;
    using System;
    using System.Threading;
    using System.Threading.Tasks;
    using Umbraco.Cms.Core.Models.PublishedContent;
    using Umbraco.Cms.Core.Web;
    using Umbraco.Cms.Web.Common.Controllers;
    using Umbraco.Extensions;

    public class JenkinsBuildController : UmbracoPageController, IVirtualPageController
    {
        private readonly IJenkinsWorker _jenkinsWorker;

        private readonly IPublishedValueFallback _publishedValueFallback;

        private readonly IUmbracoContextAccessor _umbracoContextAccessor; 

        public JenkinsBuildController(ILogger<RenderController> logger,
            ICompositeViewEngine compositeViewEngine,
            IUmbracoContextAccessor umbracoContextAccessor,
            IPublishedValueFallback publishedValueFallback,
            IJenkinsWorker jenkinsWorker
            ) : base(logger, compositeViewEngine)
        {
            _jenkinsWorker = jenkinsWorker;
            _umbracoContextAccessor = umbracoContextAccessor;
            _publishedValueFallback = publishedValueFallback;
        }

        public IPublishedContent FindContent(ActionExecutingContext actionExecutingContext)
        {
            if (_umbracoContextAccessor.TryGetUmbracoContext(out IUmbracoContext umbracoContext))
            {
                var home = umbracoContext.Content.GetAtRoot().First();

                if (home != null)
                {
                    return home.ChildrenOfType("jenkinsBuild").First();
                } 
            }

            return null;
        }

        [Route("[Controller]/{jobName}/{buildNumber}")]
        [HttpGet]
        public async Task<IActionResult> Index(string jobName, int buildNumber, string? tab = "overview", CancellationToken cancellationToken = default(CancellationToken))
        {
            if (string.IsNullOrWhiteSpace(jobName))
            {
                throw new ArgumentNullException(nameof(jobName));
            }

            var build = await _jenkinsWorker.GetBuildAsync<JenkinsBuildBase>(jobName, buildNumber, cancellationToken);

            var model = new JenkinsBuildPage(CurrentPage, _publishedValueFallback, build)
            {
                ConsoleHtml = await _jenkinsWorker.GetBuildConsoleHtmlAsync(jobName, buildNumber, cancellationToken),
                Tab = tab,
                JobName = jobName,
            };

            return View("~/Views/Jenkins/Build/JenkinsBuild.cshtml", model);
        }

        [Route("[Controller]/{jobName}/{buildNumber}/OverviewTab")]
        [HttpGet]
        public async Task<IActionResult> OverviewTab(string jobName, int buildNumber, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (string.IsNullOrWhiteSpace(jobName))
            {
                throw new ArgumentNullException(nameof(jobName));
            }

            var build = await _jenkinsWorker.GetBuildAsync<JenkinsBuildBase>(jobName, buildNumber, cancellationToken);

            var model = new JenkinsBuildPage(CurrentPage, _publishedValueFallback, build)
            {
                ConsoleHtml = await _jenkinsWorker.GetBuildConsoleHtmlAsync(jobName, buildNumber, cancellationToken),
                JobName = jobName,
            };

            return View("~/Views/Jenkins/Build/Partials/_overviewTab.cshtml", model);
        }


        [Route("[Controller]/{jobName}/{buildNumber}/ConsoleTab")]
        [HttpGet]
        public async Task<IActionResult> ConsoleTab(string jobName, int buildNumber, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (string.IsNullOrWhiteSpace(jobName))
            {
                throw new ArgumentNullException(nameof(jobName));
            }

            var build = await _jenkinsWorker.GetBuildAsync<JenkinsBuildBase>(jobName, buildNumber, cancellationToken);

            var model = new JenkinsBuildPage(CurrentPage, _publishedValueFallback, build)
            {
                ConsoleHtml = await _jenkinsWorker.GetBuildConsoleHtmlAsync(jobName, buildNumber, cancellationToken),
                JobName = jobName,
            };

            return PartialView("~/Views/Jenkins/Build/Partials/_consoleTab.cshtml", model);
        }
    }
}

Cds.TestDashboard.Web/Views/Jenkins/JenkinsFreeStyleJob.cshtml
@using JenkinsNET.Models
@using Cds.TestDashboard.Core.Models.Pages
@using Newtonsoft.Json 
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<JenkinsJobPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = "~/Views/Master.cshtml";
}

<header>
    <div class="header__title">
        <h1>@Model.Name</h1>
        
        <partial name="_breadcrumb" />
    </div>
</header>

<div class="main-content">
    <section class="row">
        <div class="col-2">
            <div class="card card--default">
                <div class="card__header">
                    <h2>Most Recent Build</h2>
                </div>
                <div class="card__body">
                    @{
                        var chartId = Guid.NewGuid();
                    }

                    <script>
                        window['chart-@chartId'] = {
                            type: 'pie',
                            data: {
                                labels: [
                                    'Failed',
                                    'Passed',
                                    'Skipped'
                                ],
                                datasets: [{
                                    label: 'My First Dataset',
                                    data: [@Model.LastBuild.PassCount, @Model.LastBuild.PassCount, @Model.LastBuild.SkipCount],
                                    backgroundColor: [
                                        'rgb(255, 99, 132)',
                                        'rgb(54, 162, 235)',
                                        'rgb(255, 205, 86)'
                                    ],
                                    hoverOffset: 4
                                }]
                            },
                            options: {
                                responsive: true,
                                maintainAspectRatio: false
                            }
                        };
                    </script>

                    <div><canvas class="js-chart" data-config-id="chart-@chartId"></canvas></div>
                </div>
            </div>
        </div>
        <div class="col-10">
            <div class="card card--default">
                <div class="card__header">
                    <h2>Build Durations</h2>
                </div>
                <div class="card__body">
                    @{
                        var chart2Id = Guid.NewGuid();
                        List<int> labels = new List<int>();
                        List<long> values = new List<long>();

                        foreach (var item in Model.Durations.OrderBy(m => m.Key))
                        {
                            labels.Add(item.Key);
                            values.Add(item.Value);
                        }
                    }

                    <script>
                        window['chart-@chart2Id'] = {
                            type: 'line',
                            data: {
                                labels: @JsonConvert.SerializeObject(labels),
                                datasets: [{
                                    label: 'My First Dataset',
                                    data: @JsonConvert.SerializeObject(values),
                                    fill: false,
                                    borderColor: 'rgb(75, 192, 192)',
                                    tension: 0.1
                                }]
                            },
                            options: {
                                responsive: true,
                                maintainAspectRatio: false
                            }
                        };
                    </script>
                    <div style="position: relative; min-width: 30vw; height: 30vh;"><canvas class="js-chart" data-config-id="chart-@chart2Id"></canvas></div>
                </div>
            </div>
        </div>
    </section>

    <section class="row">
        <div class="col-12">
            <div class="card card--default">
                <div class="card__header">
                    <h2>Builds</h2>
                </div>
                <div class="card__body">
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var build in ((JenkinsFreeStyleJob)Model.Job).Builds)
                            {
                                <tr>
                                    <td>
                                        Build @build.Number
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Index", "JenkinsBuild", new { jobName = Model.Job.Name, buildNumber = build.Number })">link</a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>